remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Under construction
description: Under construction
domain: facelessg00n.github.io   # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://facelessg00n.github.io  # the base hostname and protocol for your site, e.g. http://example.com
